[package]
name = "tbg"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
uuid = { version = "1.3", features = ["v4"] }


[dependencies]
termion = "1.5"
rusqlite = { version = "0.33.0", features = ["bundled"] }
uuid = { version = "1.3", features = ["v4"] }
